### PR TITLE
Release eventid v1.0

### PR DESCRIPTION
**Pull request by JustinBeckwith**
This pull request was generated using releasetool.

### CODE REVIEW

**Comment by ofrobots** [comment]
IMO, there is no urgency in getting something like this released. There is no business value I see in releasing this. If this was including a feature or fix, 👍. Until then 👎.

**Comment by JustinBeckwith** [comment]
So I messed up the release here, which is why I closed it.  But - the feature is having TypeScript types out of the box.  Not a huge deal, but it would be nice since we're in the process of making Spanner (which uses this) fully TypeScriptalicious.  Any reason not to ship a 1.0 with types?

**Comment by ofrobots** [comment]
Oh! I didn't know `spanner` was picking this up as a dep. Can you point me to the PR?

**Comment by JustinBeckwith** [comment]
Ok I got my wires crossed :) This is in [nodejs-logging](https://github.com/googleapis/nodejs-logging/blob/a55c43e19a32347c4a51cf81a4f4fbe0286fd215/src/entry.ts#L19), which we're also trying to typescripify.

**Comment by ofrobots** [comment]
Fair enough. Given that `logging` is the only public dependent for this module, this release makes sense.

**Pull request closed without merging**
